name: Unzip archive
on:
  workflow_dispatch:
jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Unzip
        run: |
          unzip "bioquest (6).zip" -d bioquest_files/
          rm "bioquest (6).zip"
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "解压 bioquest (6).zip"
          git push
